### ISSUE TITLE
Scanner does not work on iOS devices

### ISSUE THREAD

**Issue by Tanitolus** [moho4141/flutter_web_qrcode_scanner#3]
When loading on web (using safari/chrome), ios users see a blank page (works fine on android though)

Thank you so much for this package :)

**Comment by moho4141** [comment]
Thank you for reaching out and reporting the issue. I appreciate your diligence in helping us improve the package. After reviewing your concern, I performed thorough testing on both Mac and iPhone devices, and I'm pleased to inform you that the package successfully passed the tests on these platforms.
I would like you to retest the package and notify us. Please consider the following points:

**Protocol Usage:** Ensure that you are using the https protocol instead of http.
**Internet Connection:** Make sure that you have a stable and reliable internet connection. 
**Package Testing:** I recommend testing the package on our example website specifically designed for this purpose. You can access it at the following link: [https://flutter-web-qrcode-scanner.mahamed-ebraheem.sd/](https://flutter-web-qrcode-scanner.mahamed-ebraheem.sd/)

**Comment by Tanitolus** [comment]
I've checked it now and it works. thanks!
